---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alpine
    spec:
      volumes:
        - name: nas
          persistentVolumeClaim:
            claimName: alpine-pvc
      containers:
        - image: alpine
          name: alpine
          volumeMounts:
            - mountPath: "/mnt/nas"
              name: nas
          command: ["sleep", "infinity"]
