---
- name: Download k3d "{{ k3d_version }}"
  get_url:
    url: https://raw.githubusercontent.com/rancher/k3d/main/install.sh
    dest: /tmp/ansible/install_k3d.sh

- name: Install k3d
  shell: |
    cat /tmp/ansible/install_k3d.sh | TAG="{{ k3d_version }}" bash
  args:
    creates: /usr/local/bin/k3d

- name: k3d completion
  become: yes
  become_user: root
  shell: |
    k3d completion "$(basename "${SHELL}")" > /etc/bash_completion.d/k3d
  args:
    creates: /etc/bash_completion.d/k3d

- name: k3d fact
  become: yes
  become_user: root
  shell: |
    echo "{\"version\" : \"$(k3d --version | head -1 | sed "s:.* ::")\"}" > /etc/ansible/facts.d/k3d
  args:
    creates: /etc/ansible/facts.d/k3d
