---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Install dependencies
  become: yes
  become_user: root
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Add Docker GPG apt Key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  become_user: root
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
    state: present

- name: Install Docker
  become: yes
  become_user: root
  package:
    name: docker-ce
    state: present

- name: Ensure ansible user is added to the docker group
  become: yes
  become_user: root
  user:
    name: "{{ ansible_user }}"
    groups: ["docker"]
    append: true

- name: Ensure Docker is started and enabled at boot
  become: yes
  become_user: root
  service:
    name: docker
    state: started
    enabled: true

- name: Reboot the machine to guarantee that groups have been applied
  become: yes
  become_user: root
  reboot:
    reboot_timeout: 300
  when: ansible_local["k3d"]["bin"]["docker"] == ""
