---
- name: Copy resources
  ansible.builtin.copy:
    src: ../resources/
    dest: /var/ansible/resources/

- name: Deploy local registry
  shell: |
    k3d registry list k3d-registry.localhost || k3d registry create registry.localhost -p 5000
    while ! curl -s http://k3d-registry.localhost:5000/v2/_catalog; do
      sleep 2
    done

- name: Deploy k3d cluster
  shell: |
    CLUSTER_NAME="k3s-$(hostname -s)-${USER}"
    k3d cluster list "${CLUSTER_NAME}" 2>/dev/null || k3d cluster create \
        ${CLUSTER_NAME} \
        --agents=1 \
        --api-port=$(shuf -i 6000-7000 -n 1) \
        --image=rancher/k3s:latest \
        --k3s-server-arg=--cluster-domain=${CLUSTER_NAME}.local \
        --k3s-server-arg=--tls-san=$(hostname -i | cut -d" " -f1) \
        --k3s-server-arg=--tls-san=$(hostname -f) \
        --kubeconfig-switch-context \
        --port=443:443@loadbalancer \
        --registry-use=k3d-registry.localhost:5000 \
        --registry-config="/var/ansible/resources/k3s/registry.yml" \
        --servers=1 \
        --timeout=120s \
        --volume /mnt/nas/k3s/storage/persistentvolumes:/mnt/nas \
        --volume /mnt/nas/k3s/storage/storageclasses/local-path:/var/lib/rancher/k3s/storage || exit 1
    sed -i -e "s|https://0.0.0.0|https://$(hostname -i | cut -d" " -f1)|" "$HOME/.kube/config"
    while kubectl get pods --all-namespaces | grep -E -q -v " STATUS | Running | Completed "; do \
      sleep 5 ; \
    done

- name: System upgrade
  shell: |
    kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.6.2/system-upgrade-controller.yaml
